<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KK_VR_CameraSync</AssemblyName>
    <RootNamespace>KK_VR_CameraSync</RootNamespace>
    <TargetFramework>net35</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GameRoot Condition="'$(GameRoot)' == ''">C:\Games\Koikatu</GameRoot>
    <KKVRRoot Condition="'$(KKVRRoot)' == ''">..\KK_VR</KKVRRoot>
    <VRGINPath Condition="'$(VRGINPath)' == '' and Exists('$(GameRoot)\BepInEx\VRGIN_KKCS.dll')">$(GameRoot)\BepInEx\VRGIN_KKCS.dll</VRGINPath>
    <VRGINPath Condition="'$(VRGINPath)' == ''">$(KKVRRoot)\VRGIN_KKCS\bin\Release\net35\VRGIN_KKCS.dll</VRGINPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>$(GameRoot)\CharaStudio_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameRoot)\CharaStudio_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(GameRoot)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GameRoot)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VRGIN_KKCS">
      <HintPath>$(VRGINPath)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
